---
##########################################################
## Turn On Front Lights when Door Bell Rings or camera motion_1
##########################################################

alias: Turn On Front Lights when Door Bell Rings or camera motion_1
initial_state: 'off'

trigger:
  - platform: state
    entity_id: binary_sensor.ring_front_doorbell_ding
    from: 'off'
    to: 'on'

condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: state
    entity_id: input_boolean.disable_doorbell
    state: 'off'

action:
  - service: light.turn_on
    entity_id: light.front_yard_lights
    data:
      brightness: 255
      color_temp: 200