---
##########################################################
## Turn off front yard lights_3
##########################################################

alias: Turn off front yard lights_3
initial_state: 'off'

trigger:
  - platform: state
    entity_id: binary_sensor.cam_6_field_detection
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 00

condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'

action:
  - service: light.turn_off
    entity_id: light.front_yard_lights
    data:
      transition: 30