---

# This integration is a meta-component and configures a default
# set of integrations for Home Assistant to load. The integrations
# that will be loaded are:
#
# automation
# cloud
# config
# frontend
# history
# logbook
# map
# mobile_app
# person
# script
# ssdp
# sun
# system_health
# updater
# zeroconf

# https://www.home-assistant.io/integrations/default_config/

default_config: