#################################################################
#                                                               #
#                  Packages/Power Consumption                   #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Sensors                              #
#                                                               #
################################################################# 

sensor:

####################################################
#                                                  #
#                Sensors - Template                #
#                                                  #
####################################################

  - platform: template
    sensors: 
      total_energy:
        value_template: "{{ (states.sensor.monthly_dryer.state|float + states.sensor.monthly_washing_machine.state|float) |round(2) }}"
        friendly_name: 'Total'

      dryer_last_month:
        value_template: "{{ states.sensor.monthly_dryer.attributes.last_period }}"
        friendly_name: 'Last Month'
        
      washing_machine_last_month:
        value_template: "{{ states.sensor.monthly_washing_machine.attributes.last_period }}"
        friendly_name: 'Last Month'
        
      total_last_month:
        entity_id: sensor.monthly_total
        value_template: "{{ states.sensor.monthly_total.attributes.last_period }}"
        friendly_name: 'Last Month'
        
      remaining_days:
        friendly_name: "Month Left"
        entity_id: sensor.date
        value_template: >-
          {% if now().month in [1,3,5,7,8,10,12] %}
            {{ 31 - now().day }}
          {% elif now().month in [4,6,9,11] %}
            {{ 30 - now().day }}
          {% elif now().month == 2 and ((now().year-2000) % 4 > 0) %}
            {{ 28 - now().day }}
          {% elif now().month == 2 and ((now().year-2000) % 4 == 0) %}
            {{ 29 - now().day }}
          {% endif %}



####################################################
#                                                  #
#             Sensors - History Stats              #
#                                                  #
####################################################
        
#  - platform: history_stats
#    name: Kitchen Light
#    entity_id: switch.kitchen_light_switch
#    state: 'on'
#    type: time
#    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
#    end: '{{ now() }}'
    


#################################################################
#                                                               #
#                        Utility Meter                          #
#                                                               #
################################################################# 

utility_meter:

  monthly_dryer:
    source: sensor.dryer_energy
    cycle: monthly
    
  monthly_washing_machine:
    source: sensor.washing_machine_energy
    cycle: monthly
    
  daily_total:
    source: sensor.total_energy
    cycle: daily
    
  weekly_total:
    source: sensor.total_energy
    cycle: weekly
    
  monthly_total:
    source: sensor.total_energy
    cycle: monthly
