#################################################################
#                                                               #
#                  Packages/Energy Consumption                  #
#                                                               #
#################################################################

# Synergy Smart Home Plan Tariffs
#
# Everyday Off-peak                        (9pm to 7am)
# Peak - weekdays only                     (3pm to 9pm)
# Weekday shoulder                         (7am to 3pm)
# Weekend shoulder                         (7am to 9pm)
#
# 
# Item                                     Price inc. GST
# Supply charge                            103.3263 cents per day
# Everyday Off-peak electricity charge     15.1002 cents per unit
# Weekend shoulder electricity charge      28.7076 cents per unit
# Weekday shoulder electricity charge      28.7076 cents per unit
# Peak electricity charge                  54.8142 cents per unit 


#################################################################
#                                                               #
#                          Input Selects                        #
#                                                               #
################################################################# 

input_select:

  utility_meter_electricity_tariff:
    name: Electricity Tariff
    options:
      - everyday_offpeak
      - weekend_shoulder
      - weekday_shoulder
      - peak_weekdays


#################################################################
#                                                               #
#                          Input Numbers                        #
#                                                               #
################################################################# 

input number:

  electricity_cost_supply_charge:
    name: Electricity Supply Charge Per Day
    min: 50.0000
    max: 150.0000
    unit_of_measurement: 'c'
    initial: 103.3263
    mode: box
    icon: mdi:currency-usd

  electricity_cost_everyday_offpeak:
    name: Electricity Cost Everyday Off-Peak
    min: 10.0000
    max: 80.0000
    unit_of_measurement: 'c'
    initial: 15.1002
    mode: box
    icon: mdi:currency-usd

  electricity_cost_weekend_shoulder:
    name: Electricity Cost Weekend Shoulder
    min: 10.0000
    max: 80.0000
    unit_of_measurement: 'c'
    initial: 28.7076
    mode: box
    icon: mdi:currency-usd

  electricity_cost_weekday_shoulder:
    name: Electricity Cost Weekday Shoulder
    min: 10.0000
    max: 80.0000
    unit_of_measurement: 'c'
    initial: 28.7076
    mode: box
    icon: mdi:currency-usd

  electricity_cost_peak_weekdays:
    name: Electricity Cost Peak Weekdays
    min: 10.0000
    max: 80.0000
    unit_of_measurement: 'c'
    initial: 54.8142
    mode: box
    icon: mdi:currency-usd



#################################################################
#                                                               #
#                          Sensors                              #
#                                                               #
################################################################# 

sensor:

####################################################
#                                                  #
#                Sensors - Template                #
#                                                  #
####################################################

  - platform: template
    sensors: 
      total_energy:
        value_template: "{{ (states.sensor.monthly_dryer_energy.state|float + states.sensor.monthly_washing_machine_energy.state|float) |round(2) }}"
        friendly_name: 'Total'

      dryer_last_month:
        value_template: "{{ states.sensor.monthly_dryer_energy.attributes.last_period }}"
        friendly_name: 'Last Month'
        
      washing_machine_last_month:
        value_template: "{{ states.sensor.monthly_washing_machine_energy.attributes.last_period }}"
        friendly_name: 'Last Month'
        
      total_last_month:
        entity_id: sensor.monthly_energy_total
        value_template: "{{ states.sensor.monthly_energy_total.attributes.last_period }}"
        friendly_name: 'Last Month'
        
      month_remaining_days:
        friendly_name: "Month Left"
        entity_id: sensor.date
        value_template: >-
          {% if now().month in [1,3,5,7,8,10,12] %}
            {{ 31 - now().day }}
          {% elif now().month in [4,6,9,11] %}
            {{ 30 - now().day }}
          {% elif now().month == 2 and ((now().year-2000) % 4 > 0) %}
            {{ 28 - now().day }}
          {% elif now().month == 2 and ((now().year-2000) % 4 == 0) %}
            {{ 29 - now().day }}
          {% endif %}



####################################################
#                                                  #
#             Sensors - History Stats              #
#                                                  #
####################################################
        
#  - platform: history_stats
#    name: Kitchen Light
#    entity_id: switch.kitchen_light_switch
#    state: 'on'
#    type: time
#    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
#    end: '{{ now() }}'
    


#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################

#automation:


#################################################################
#                                                               #
#                        Utility Meter                          #
#                                                               #
################################################################# 

# Periods
  # Hourly
  # Daily     #
  # Weekly    #
  # Monthly   #
  # Quarterly #
  # Yearly

# Categories
  # Appliances
  # Lights
  # Fans
  # Climate


# Devices
# Z-Wave
  # Name                          Category
  #-------------------------------------------------------------------------------------------
  # Dishwasher                    
  # Dryer                         
  # Fountain                      
  # Fridge                        
  # Garage Light                  
  # Garden Lights                 
  # Living Room Heater            
  # Living Room Receiver          
  # Living Room Sub               
  # Office Equipment              
  # Office Mat Heater             
  # Office Monitors               
  # PVE1-Node1                    
  # PVE1-Node2                    
  # Stair LEDs                    
  # Switch1                       
  # Tower                         
  # TV                            
  # UPS                           
  # Washing Machine               
  # Wine Fridge                   


# Measurement
  # Usage
  # Cost


# Total Usage
  # Total Daily Usage Appliances
  # Total Daily Usage Lights
  # Total Daily Usage Fans
  # Total Daily Usage Climate
  ####
  # Total Daily Usage

  # Total Weekly Usage Appliances
  # Total Weekly Usage Lights
  # Total Weekly Usage Fans
  # Total Weekly Usage Climate
  ####
  # Total Weekly Usage

  # Total Monthly Usage Appliances
  # Total Monthly Usage Lights
  # Total Monthly Usage Fans
  # Total Monthly Usage Climate
  ####
  # Total Monthly Usage

  # Total Quarterly Usage Appliances
  # Total Quarterly Usage Lights
  # Total Quarterly Usage Fans
  # Total Quarterly Usage Climate
  ####
  # Total Quarterly Usage

# Comparison Usage
  # Yesterday Usage Comparison
  # Last Week Usage Comparison
  # Last Month Usage Comparison
  # Last Quarter Usage Comparison

  # This Time Last Year Usage Comparison - Day
  # This Time Last Year Usage Comparison - Week
  # This Time Last Year Usage Comparison - Month
  # This Time Last Year Usage Comparison - Quarter

# Difference Usage
  # Yesterday Usage Difference
  # Last Week Usage Difference
  # Last Month Usage Difference
  # Last Quarter Usage Difference

  # This Time Last Year Usage Difference - Day
  # This Time Last Year Usage Difference - Week
  # This Time Last Year Usage Difference - Month
  # This Time Last Year Usage Difference - Quarter




# Total Cost
  # Total Daily Cost Appliances
  # Total Daily Cost Lights
  # Total Daily Cost Fans
  # Total Daily Cost Climate
  ####
  # Total Daily Cost

  # Total Weekly Cost Appliances
  # Total Weekly Cost Lights
  # Total Weekly Cost Fans
  # Total Weekly Cost Climate
  ####
  # Total Weekly Cost

  # Total Monthly Cost Appliances
  # Total Monthly Cost Lights
  # Total Monthly Cost Fans
  # Total Monthly Cost Climate
  ####
  # Total Monthly Cost

  # Total Quarterly Cost Appliances
  # Total Quarterly Cost Lights
  # Total Quarterly Cost Fans
  # Total Quarterly Cost Climate
  ####
  # Total Quarterly Cost

# Comparison Cost
  # Yesterday Cost Comparison
  # Last Week Cost Comparison
  # Last Month Cost Comparison
  # Last Quarter Cost Comparison

  # This Time Last Year Cost Comparison - Day
  # This Time Last Year Cost Comparison - Week
  # This Time Last Year Cost Comparison - Month
  # This Time Last Year Cost Comparison - Quarter

# Difference Cost
  # Yesterday Cost Difference
  # Last Week Cost Difference
  # Last Month Cost Difference
  # Last Quarter Cost Difference

  # This Time Last Year Cost Difference - Day
  # This Time Last Year Cost Difference - Week
  # This Time Last Year Cost Difference - Month
  # This Time Last Year Cost Difference - Quarter



utility_meter:

# Daily

  monthly_dryer_energy:
    source: sensor.dryer_energy
    cycle: monthly
    tariffs:
      - everyday_offpeak
      - peak_weekdays
      - weekday_shoulder
      - weekend_shoulder
    
  monthly_washing_machine_energy:
    source: sensor.washing_machine_energy
    cycle: monthly
    tariffs:
      - everyday_offpeak
      - peak_weekdays
      - weekday_shoulder
      - weekend_shoulder

  daily_energy_total:
    source: sensor.total_energy
    cycle: daily
    tariffs:
      - everyday_offpeak
      - peak_weekdays
      - weekday_shoulder
      - weekend_shoulder
    
  weekly_energy_total:
    source: sensor.total_energy
    cycle: weekly
    tariffs:
      - everyday_offpeak
      - peak_weekdays
      - weekday_shoulder
      - weekend_shoulder
    
  monthly_energy_total:
    source: sensor.total_energy
    cycle: monthly
    tariffs:
      - everyday_offpeak
      - peak_weekdays
      - weekday_shoulder
      - weekend_shoulder
