---

alias: Blinds Up
initial_state: 'on'
trigger:
  platform: time
  at: '07:30:00'
condition:
  condition: and
  conditions:
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.james_status
        state: 'Away'
      - condition: state
        entity_id: sensor.james_status
        state: 'Extended Away'
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.denise_status
        state: 'Away'
      - condition: state
        entity_id: sensor.denise_status
        state: 'Extended Away'
action:
  service: cover.open_cover
  entity_id: cover.living_room_blinds