---
esphome:
  name: ${id}
  platform: ESP8266
  board: d1_mini
  
  <<: !include ../esphome/leds/status.yaml

<<: !include ../wifi_fast_connect.yaml
<<: !include ../ota.yaml
<<: !include ../api.yaml
<<: !include ../logger_info.yaml

binary_sensor:
  - !include ../binary_sensors/status.yaml

light:
  - !include ../lights/status_led.yaml

output:
  - !include ../outputs/status_led.yaml

switch:
  - !include ../switches/relay_internal.yaml
  - !include ../switches/relay_status_led.yaml