---
  
id: send_notification_of_rss_feed_title_when_updated
alias: Send notification of RSS feed title when updated
initial_state: 'on'
trigger:
  platform: event
  event_type: feedreader

action:
  - service: notify.ios_james_phone
    data_template:
      title: "New HA Podcast available"
      message: "New HA Podcast - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
      data:
        url: "https://hasspodcast.io/"

  - service: persistent_notification.create
    data_template:
      title: "New HA Podcast available"
      message: "New Podcast available - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
      notification_id: "update_available"