---

id: system_travis_build_passed
alias: System Travis Build Passed
initial_state: 'on'
trigger:
  - platform: state
    entity_id: sensor.jamessnappyhomeassistantconfig_last_build_state
    from: "started"
    to: "passed"
action:
  - service: notify.ios_james_phone
    data_template:
      message: >
        Travis build passed! {{ "\uD83D\uDC4D" }}
      data:
        url: https://travis-ci.org/james-snappy/Home-AssistantConfig
#      - service: hassio.addon_start
#        data:
#          addon: core_git_pull