---
wifi:
  ssid: !secret ssid
  password: !secret ssid_password
  domain: !secret domain

  # Disable Reboot on Wifi Disconnections
  reboot_timeout: 0s

  power_save_mode: none

  # Directly connects to WiFi network without doing a full scan first.
  # Can significantly improve connection times
  fast_connect: true