---

alias: All lights off at 11pm if not home
initial_state: 'on'
trigger:
  - platform: time
    at: '23:00'
condition:
  condition: and
  conditions:
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.james_status
          state: 'Away'
        - condition: state
          entity_id: sensor.james_status
          state: 'Extended Away'
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.denise_status
          state: 'Away'
        - condition: state
          entity_id: sensor.denise_status
          state: 'Extended Away'
action:
  - service: light.turn_off
    data:
      entity_id: light.outside_lights
      transition: 60
  - service: light.turn_off
    data:
      entity_id: light.inside_lights
      transition: 60