---

alias: Dining and Kitchen Lights off while we are away
initial_state: 'on'
trigger:
  - platform: state
    entity_id: binary_sensor.dining_room_pir
    to: 'off'
    for: '00:15:00'
condition:
  condition: and
  conditions:
  - condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.5
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.james_status
        state: 'Away'
      - condition: state
        entity_id: sensor.james_status
        state: 'Extended Away'
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.denise_status
        state: 'Away'
      - condition: state
        entity_id: sensor.denise_status
        state: 'Extended Away'
action:
- service: light.turn_off
  data:
    entity_id: light.dining_room_downlights
    transition: 30
- service: light.turn_off
  data:
    entity_id: light.kitchen_downlights
    transition: 30