---

alias: Welcome Home Lights
initial_state: 'on'
trigger:
- platform: state
  entity_id: sensor.james_status
  to: 'Just Arrived'
- platform: state
  entity_id: sensor.denise_status
  to: 'Just Arrived'
condition:
  condition: and
  conditions:
    - condition: sun
      after: sunset
      after_offset: "-00:45:00"
    - condition: template
      value_template: >
        {% if states("sensor.james_status") != "Home" and states("sensor.denise_status") != "Home"%}
          true
        {% else %}
          false
        {% endif %}
action:
  - service: script.turn_on
    data:
      entity_id: script.lights_welcome_home