---
button_1_gpio: GPIO0
button_2_gpio: GPIO9
button_3_gpio: GPIO10
button_4_gpio: GPIO14

led_status_gpio: GPIO13

relay_1_gpio: GPIO12
relay_2_gpio: GPIO5
relay_3_gpio: GPIO4
relay_4_gpio: GPIO15

rx_gpio: GPIO3
tx_gpio: GPIO1